### ISSUE TITLE
fatal error: 'taos.h' file not found

### ISSUE THREAD

**Issue by HendSame** [taosdata/Bailongma#10]
# github.com/taosdata/driver-go/taosSql
../../../../gowork/pkg/mod/github.com/taosdata/driver-go@v0.0.0-20201113094317-050667e5b4d0/taosSql/result.go:21:10: fatal error: 'taos.h' file not found
#include <taos.h>
         ^~~~~~~~
1 error generated.

**Comment by HendSame** [comment]
@sangshuduo

**Comment by sangshuduo** [comment]
没装客户端安装包？

**Comment by HendSame** [comment]
客户端安装包是？

**Comment by HendSame** [comment]
按照文档编译的，好像没涉及你说的这个唉

**Comment by HendSame** [comment]
![image](https://user-images.githubusercontent.com/9264192/106579354-916aa400-657b-11eb-9fd0-5fcc98aaa0d1.png)
该下的包也下了的

**Comment by sangshuduo** [comment]
https://www.taosdata.com/cn/all-downloads/

**Comment by HendSame** [comment]
@sangshuduo 编译成功了，多谢，对了 --tdengine-ip 这个参数可以设置多个IP吗，还是说集群模式下只要设置任意一个就好了？

**Comment by sangshuduo** [comment]
对，集群模式连任意一个都可以
