### ISSUE TITLE
prometheus 配置了BLM 没有数据写到TDengine，也没有报错

### ISSUE THREAD

**Issue by HendSame** [taosdata/Bailongma#11]
问题：prometheus 配置了BLM 没有数据写到TDengine，也没有报错
prometheus 版本：2.24.0
TDengine 版本：2.0.15

1、prometheus的启动日志：
![image](https://user-images.githubusercontent.com/9264192/106688739-a1c96000-6609-11eb-8fec-badfee704b94.png)
2、prometheus的配置：
![image](https://user-images.githubusercontent.com/9264192/106688798-c6253c80-6609-11eb-9f92-54e996ad5681.png)
3、BIM服务也是正常的，在安装了prometheus的机器上，直接http请求：
![image](https://user-images.githubusercontent.com/9264192/106688933-097fab00-660a-11eb-8000-bdaa0d44f7e9.png)
4、BLM的启动参数，并且进程也在的：
![image](https://user-images.githubusercontent.com/9264192/106689001-33d16880-660a-11eb-95f9-a9ff1886398c.png)
5、然后TDengine的机器上查不到数据，连数据库都没有创建：
![image](https://user-images.githubusercontent.com/9264192/106689074-55caeb00-660a-11eb-904b-5a770b028c65.png)
6、实际在grafana里面是有数据写入prometheus的：
![image](https://user-images.githubusercontent.com/9264192/106689164-76934080-660a-11eb-8f57-926a27e20eb1.png)

**Comment by HendSame** [comment]
@sangshuduo @liuyq-617 @liu0x54 @fangpanpan  有时间帮忙看看么

**Comment by sangshuduo** [comment]
在同一台机器上跑 tdengine，blm 和 prometheus 可以吗？

**Comment by HendSame** [comment]
@sangshuduo 都在同一台机器就可以，这是什么原因，主要是这几台机器之前网络也是通的。

**Comment by HendSame** [comment]
telnet  目标的TDengine 机器的 6030 端口也是通的

**Comment by sangshuduo** [comment]
tcpdump 抓包看看有没有数据包

**Comment by anjia0532** [comment]
没有自动建库，手动创建后，又报表没有创建
![image](https://user-images.githubusercontent.com/15098916/110770601-784cc580-8294-11eb-864e-cea0bd1ac060.png)

**Comment by anjia0532** [comment]
```bash
BLM_PRM2021/03/11 10:24:11 server.go:155: host: ip
BLM_PRM2021/03/11 10:24:11 server.go:156: 172.18.5.18:0
BLM_PRM2021/03/11 10:24:11 server.go:157:   port:
BLM_PRM2021/03/11 10:24:11 server.go:158: 10203
BLM_PRM2021/03/11 10:24:11 server.go:159:   database:
BLM_PRM2021/03/11 10:24:11 server.go:160: prometheus
BLM_PRM2021/03/11 10:24:19 server.go:596: taos_connect() fail!
BLM_PRM2021/03/11 10:24:23 server.go:588: execSql Error: taos_connect() fail! sqlcmd: alter table apisix_etcd_modify_indexes add tag t_instance binary(128)

BLM_PRM2021/03/11 10:24:23 server.go:403: taos_connect() fail!
```

**Comment by anjia0532** [comment]
创建表和数据库的连接字符串不对吧？
官方文档golang的是user:password@/tcp(host:port)/dbname
但是实际建表用的rpc连接，打开连接时用的daemonIP的取值是ip:0,也就是端口写死的是0，不知道跟这个有没有关系
![image](https://user-images.githubusercontent.com/15098916/110877630-a40f9000-8314-11eb-9206-a2f27d860db6.png)
![image](https://user-images.githubusercontent.com/15098916/110877700-c1dcf500-8314-11eb-8149-a8bf633eb8a2.png)
![image](https://user-images.githubusercontent.com/15098916/110877742-d5885b80-8314-11eb-9edb-48638dc948be.png)

**Comment by sangshuduo** [comment]
@HendSame 这个问题还存在吗？

**Comment by HendSame** [comment]
之前是都在一台机器是可以的，后来还没来得及验证多台机器情况。刚好这几天准备再试试，到时候我在这里反馈下

**Comment by HendSame** [comment]
@sangshuduo 

会报这些错误，和上面的 @anjia0532  说的一样

BLM_PRM2021/05/07 13:40:45 server.go:155: host: ip
BLM_PRM2021/05/07 13:40:45 server.go:156: 10.70.21.224:0
BLM_PRM2021/05/07 13:40:45 server.go:157:   port:
BLM_PRM2021/05/07 13:40:45 server.go:158: 8989
BLM_PRM2021/05/07 13:40:45 server.go:159:   database:
BLM_PRM2021/05/07 13:40:45 server.go:160: prometheus
BLM_PRM2021/05/07 13:40:45 server.go:596: Invalid database name
BLM_PRM2021/05/07 13:40:48 server.go:588: execSql Error: taos_connect() fail! sqlcmd: create table if not exists go_gc_duration_seconds (ts timestamp,
value double) tags(taghash binary(34),t_instance binary(128),t_job binary(128),t_quantile binary(128))

**Comment by sangshuduo** [comment]
@HendSame 可以试一下在跑 BLM 这台机器上用 taos 客户端连另一个机器的 taosd 进行一些基本操作，比如建库、建表、插入数据、查询，看是不是网络端口没开或者 FQDN 不一致导致的连接问题

**Comment by HendSame** [comment]
@sangshuduo 
用taos 客户端是可以的

![image](https://user-images.githubusercontent.com/9264192/117407114-aa9b3c00-af40-11eb-9e67-a29a83cd7159.png)

**Comment by HendSame** [comment]
@zitsen 
这个有异常。

![image](https://user-images.githubusercontent.com/9264192/117530057-a7ba4d00-b00d-11eb-8a44-b4a1de89d69b.png)

**Comment by zitsen** [comment]
经验来看，应该是fqdn没有配置好。您的情况应该是TDengine和客户端运行节点不一样，而客户端的host没有配置的原因。解决方法应该是：
1. 添加hostname解析到/etc/hosts
2. 使用hostname作为configHost

**Comment by zitsen** [comment]
我今天休假了，不方便处理，你可以搜下文档对fqdn的说明，有什么问题可以加我同名微信。
