### ISSUE TITLE
error:too many open files

### ISSUE THREAD

**Issue by start1943** [taosdata/Bailongma#17]
![image](https://user-images.githubusercontent.com/35452394/119461034-e40ddd00-bd71-11eb-9941-86408423609a.png)

**Comment by sangshuduo** [comment]
请问这是如何操作产生的？

**Comment by start1943** [comment]
随着启动时间，进程打开的文件句柄一直不断增加，直到超限报错，内存也一直涨。数据有正常写入。

**Comment by sangshuduo** [comment]
可以再拉一下代码编译一下，正好刚修了一个内存方面的bug
