### ISSUE TITLE
启动报错 connection refused

### ISSUE THREAD

**Issue by xxj123go** [taosdata/Bailongma#19]
./blm_prometheus -port 8088 启动，终端直接报错
`Get "http://172.23.11.4:6020/rest/sql": dial tcp 172.23.11.4:6020: connect: connection refused
Get "http://172.23.11.4:6020/rest/sql": dial tcp 172.23.11.4:6020: connect: connection refused
Get "http://172.23.11.4:6020/rest/sql": dial tcp 172.23.11.4:6020: connect: connection refused
Get "http://172.23.11.4:6020/rest/sql": dial tcp 172.23.11.4:6020: connect: connection refused
Get "http://172.23.11.4:6020/rest/sql": dial tcp 172.23.11.4:6020: connect: connection refused
Get "http://172.23.11.4:6020/rest/sql": dial tcp 172.23.11.4:6020: connect: connection refused
Get "http://172.23.11.4:6020/rest/sql": dial tcp 172.23.11.4:6020: connect: connection refused
Get "http://172.23.11.4:6020/rest/sql": dial tcp 172.23.11.4:6020: connect: connection refused`

查看taosd log 如下：
`06/08 20:35:32.069964 00023174 MND ERROR msg:0x7f6e44000d60, app:0x66a table:0.prometheus.mysql_info_schema_table_size, failed to get table meta, table not exist
06/08 20:35:32.070581 00023175 MND ERROR msg:0x7f6e44000d60, app:0x66c table:0.prometheus.mysql_info_schema_table_size, failed to get table meta, table not exist
06/08 20:35:32.071263 00023174 MND ERROR msg:0x7f6e44000d60, app:0x66e table:0.prometheus.mysql_info_schema_table_size, failed to get table meta, table not exist
06/08 20:35:32.071779 00023175 MND ERROR msg:0x7f6e44000d60, app:0x670 table:0.prometheus.mysql_info_schema_table_size, failed to get table meta, table not exist
06/08 20:35:32.072324 00023174 MND ERROR msg:0x7f6e44000d60, app:0x672 table:0.prometheus.mysql_info_schema_table_size, failed to get table meta, table not exist
06/08 20:35:32.072893 00023175 MND ERROR msg:0x7f6e44000d60, app:0x674 table:0.prometheus.mysql_info_schema_table_size, failed to get table meta, table not exist
06/08 20:35:32.073430 00023174 MND ERROR msg:0x7f6e44000d60, app:0x676 table:0.prometheus.mysql_info_schema_table_size, failed to get table meta, table not exist
06/08 20:35:33.020489 00023174 MND ERROR msg:0x7f6e44000d60, app:0x678 table:0.prometheus.md5_ed032e52a5b5bb7a4b190fad66074a46, failed to get table meta, table not exist`

文档说库和表会自动创建，但实际log显示都没创建

**Comment by sangshuduo** [comment]
版本太老了，新版本的端口已经改成了 6041
