### ISSUE TITLE
 The file "server.go" can't build in TDengine 2.0.3.1 (blm_promepheus)

### ISSUE THREAD

**Issue by navyxhj** [taosdata/Bailongma#4]
I want to rebuild the project as directed by the link：https://www.taosdata.com/cn/documentation/insert/#Prometheus直接写入 
But I cannot go build, and get ERR:

> execSql Error: syntax error near ")
> " sqlcmd: create table if not exists MD5_648e4536f5d4184314287d187677867c using node_network_address_assign_type tags("623716d73194f57a558f0d1cb4964378",)

I modify the file "server.go" and add a line after line 529:

> line 529: sqlcmd = sqlcmdhead + md5V2(tagHash) + "\"," + sqlcmd
> line 530: sqlcmd = strings.Replace(sqlcmd, ",)\n", ")\n", -1)

But it still cannot run normally after modification. Attached is the generated error log, please help update the code or indicate whether there is a problem in my configuration.
This is the  table of project configuration:
| ServerName | IP            | Port      | APP              |
| ---------- | ------------- | --------- | ---------------- |
| taos1      | 10.197.190.17 | 6030~6042 | Tdengine 2.0.3.1 |
| taos2      | 10.197.190.18 | 6030~6042 | Tdengine 2.0.3.1 |
| taos3      | 10.197.190.19 | 6030~6042 | Tdengine 2.0.3.1 |
| app        | 10.197.190.20 | 3000      | Grafana 7.1.5    |
|            |               |           | Telegraf         |
|            |               | 6051      | blm_telegraf     |
| Prometheus | 10.197.190.21 | 9090      | Prometheus       |
|            |               | 6052      | blm_prometheus   |

[blm_prometheus.log](https://github.com/taosdata/Bailongma/files/5340078/blm_prometheus.log)
[prometheus.yml.log](https://github.com/taosdata/Bailongma/files/5340089/prometheus.yml.log)
[server.go.log](https://github.com/taosdata/Bailongma/files/5340092/server.go.log)
[taosdlog.0.log](https://github.com/taosdata/Bailongma/files/5340093/taosdlog.0.log)

**Comment by sangshuduo** [comment]
please pull again and run "go mod init blm\_prometheus" and "go build".
